name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - run: id
      - run: ls -l
      - run: sudo chown -R votca:votca .
      - run: mkdir build && cd build && cmake ..
      - run: make
      - name: ls
        run: ls -R
