name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: votca/buildenv:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - run: .github/workflows/build.sh
